openapi: 3.0.0
info:
  version: 1.23.0
  title: Mini Dashboard API
  description: >
    The Mini Dashboard API is a modern REST API based on the OpenAPI
    specification. Date: October 7, 2022. [Recent
    Updates](https://mini.io/whats-new/)
  contact:
    name: Mini Dashboard Developer Community
    url: https://mini.io/community
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.mini.com/api/v1

security:
  - mini_api_key: []
components:
  securitySchemes:
    mini_api_key:
      type: apiKey
      name: X-Mini-Dashboard-API-Key
      in: header
      description: Secret to access the API
      
paths:
  /organizations:
    get:
      operationId: getOrganizations
      description: List the organizations that the user has privileges on
      summary: List Organizations
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Organization Identifier
                    name:
                      type: string
                      description: Organization Name
                    url:
                      type: string
                      description: Organization Url
                    api:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          description: Enable API access
                      description: API settings"
                    licensing:
                      type: object
                      properties:
                        model:
                          type: string
                          enum:
                            - co-term
                            - per-device
                            - subscription
                          description: "Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'."
                      description: Licensing settings
                    cloud:
                      type: object
                      properties:
                        region:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of theregion
                          description: Region details
                      description: Cloud infrastructure details
      tags:
        - read
    post:
      operationId: createOrganization
      description: Create a new organization
      summary: Create Organization
      requestBody:
        description: Details of the organization to create
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the organization
              required:
                - name
            examples:
              AmsterdamOffice:
                value:
                  name: Amsterdam Office
                  licensing:
                    model: subscription
        required: true
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization Identifier
                  name:
                    type: string
                    description: Organization Name
                  url:
                    type: string
                    description: Organization Url
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API related settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing related settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region info
                    description: Data for this organization
      tags:
        - configure
  /organizations/{id}:
    get:
      operationId: getOrganization
      description: Fetch details for the specified organization
      summary: Get Organization Details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: Amsterdam
          description: Organization Identifier
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Organization Identifier
                  name:
                    type: string
                    description: Organization Name
                  url:
                    type: string
                    description: Organization Url
                  api:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        description: Enable API access
                    description: API settings
                  licensing:
                    type: object
                    properties:
                      model:
                        type: string
                        enum:
                          - co-term
                          - per-device
                          - subscription
                        description: Organization licensing model. Can be 'co-term', 'per-device', or 'subscription'.
                    description: Licensing settings
                  cloud:
                    type: object
                    properties:
                      region:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of region
                        description: Region details
                    description: Cloud infrastructure details
      tags:
        - read
    delete:
      operationId: deleteOrganization
      description: Removes the organization with the provided identifier
      summary: Delete Organization
      parameters:
        - name: id
          in: path
          schema:
            type: string
            example: Amsterdam
          required: true
          description: Organization Identifier
      responses:
        '204':
          description: Success
      tags:
        - configure 
  
tags:
  - name: read
    description: "Read Operations"
  - name: configure
    description: "Read/Write Operations"